services:
  hermit:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    network_mode: host # Bypass Docker NAT for 100% Direct P2P Tailscale connections
    privileged: true
    env_file:
      - .env
    volumes:
      # Mount the whole project directory so code updates are hot-reloaded
      - .:/app
      - /app/_build
      - ${HOME}/.hermit/dev-storage:/app/storage
    environment:
      - MIX_ENV=dev
      - PHX_SERVER=true
      - PORT=3000
      - STORAGE_BASE_PATH=/app/storage
    restart: "on-failure:5"
