defmodule HermitWeb.DNSController do
  use HermitWeb, :controller
  import Bitwise
  require Logger

  def query(conn, %{"doh_token" => doh_token} = params) do
    case Hermit.Vpn.DnsEndpoint.get_by_doh_token(doh_token) do
      nil ->
        conn
        |> put_status(404)
        |> text("DNS Endpoint not found")

      endpoint ->
        endpoint_id = endpoint.id

        case get_dns_packet(conn, params) do
          {:ok, query_packet} ->
            case Registry.lookup(Hermit.Vpn.Registry, {:dns_server, endpoint_id}) do
              [{pid, _}] ->
                client_ip = get_client_ip(conn)
                device_name = get_device_name(conn)

                result =
                  try do
                    GenServer.call(
                      pid,
                      {:resolve_query, query_packet, {:doh, client_ip, device_name}},
                      4000
                    )
                  catch
                    :exit, {:timeout, _} ->
                      Logger.error("DNS query timed out for endpoint: #{endpoint_id}")
                      {:servfail, build_servfail_packet(query_packet)}

                    :exit, reason ->
                      Logger.error(
                        "DNS Server call exited for endpoint #{endpoint_id}: #{inspect(reason)}"
                      )

                      {:servfail, build_servfail_packet(query_packet)}
                  end

                case result do
                  {:ok, response_packet} ->
                    conn
                    |> put_resp_header("content-type", "application/dns-message")
                    |> send_resp(200, response_packet)

                  {:servfail, servfail_packet} ->
                    conn
                    |> put_resp_header("content-type", "application/dns-message")
                    |> send_resp(200, servfail_packet)

                  {:error, reason} ->
                    Logger.error("DNS Server call failed: #{inspect(reason)}")

                    conn
                    |> put_status(500)
                    |> text("Internal Server Error")
                end

              [] ->
                conn
                |> put_status(404)
                |> text("DNS Server not running for endpoint")
            end

          {:error, :missing_dns_parameter} ->
            port_suffix = if conn.port in [80, 443], do: "", else: ":#{conn.port}"
            server_url = "https://#{conn.host}#{port_suffix}/dns-query/#{doh_token}"
            render_mobile_config_page(conn, endpoint, server_url)

          {:error, reason} ->
            Logger.warning("Failed to get DNS packet from request: #{inspect(reason)}")

            conn
            |> put_status(400)
            |> text("Bad Request")
        end
    end
  end

  def mobileconfig(conn, %{"doh_token" => doh_token}) do
    case Hermit.Vpn.DnsEndpoint.get_by_doh_token(doh_token) do
      nil ->
        conn
        |> put_status(404)
        |> text("DNS Endpoint not found")

      endpoint ->
        port_suffix = if conn.port in [80, 443], do: "", else: ":#{conn.port}"
        server_url = "https://#{conn.host}#{port_suffix}/dns-query/#{doh_token}"

        payload_uuid = generate_uuid()
        profile_uuid = generate_uuid()

        xml = """
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
          <key>PayloadContent</key>
          <array>
            <dict>
              <key>DNSSettings</key>
              <dict>
                <key>DNSProtocol</key>
                <string>HTTPS</string>
                <key>ServerURL</key>
                <string>#{server_url}</string>
              </dict>
              <key>PayloadDescription</key>
              <string>Configures encrypted DNS-over-HTTPS (DoH) for Hermit DNS Endpoint: #{endpoint.name}</string>
              <key>PayloadDisplayName</key>
              <string>Hermit DNS - #{endpoint.name}</string>
              <key>PayloadIdentifier</key>
              <string>com.hermit.dns.doh.#{doh_token}</string>
              <key>PayloadType</key>
              <string>com.apple.dnsSettings.managed</string>
              <key>PayloadUUID</key>
              <string>#{payload_uuid}</string>
              <key>PayloadVersion</key>
              <integer>1</integer>
            </dict>
          </array>
          <key>PayloadDescription</key>
          <string>Encrypted DNS Configuration Profile generated by Hermit.</string>
          <key>PayloadDisplayName</key>
          <string>Hermit Encrypted DNS (#{endpoint.name})</string>
          <key>PayloadIdentifier</key>
          <string>com.hermit.dns.profile.#{doh_token}</string>
          <key>PayloadType</key>
          <string>Configuration</string>
          <key>PayloadUUID</key>
          <string>#{profile_uuid}</string>
          <key>PayloadVersion</key>
          <integer>1</integer>
        </dict>
        </plist>
        """

        # Slugify endpoint name for filename safety
        safe_name = String.replace(endpoint.name, ~r/[^a-zA-Z0-9_\-]/, "_")

        conn
        |> put_resp_content_type("application/x-apple-aspen-config")
        |> put_resp_header(
          "content-disposition",
          "attachment; filename=\"hermit_dns_#{safe_name}.mobileconfig\""
        )
        |> send_resp(200, sign_profile(xml))
    end
  end

  defp sign_profile(xml) do
    base_path = Application.get_env(:hermit, :storage)[:base_path] || File.cwd!()

    phx_host =
      System.get_env("PHX_HOST") || Application.get_env(:hermit, HermitWeb.Endpoint)[:url][:host] ||
        "localhost"

    cert_dir = Path.join([base_path, "certs", phx_host])

    key_path = Path.join(cert_dir, "privkey.pem")
    cert_path = Path.join(cert_dir, "cert.pem")

    generate_self_signed_cert(cert_dir, phx_host)

    cond do
      File.exists?(key_path) and File.exists?(cert_path) ->
        # Use openssl to sign the plist file as DER format CMS message via a temp file to avoid missing :input option in System.cmd
        temp_xml_path = Path.join(System.tmp_dir!(), "temp_profile_#{generate_uuid()}.xml")
        File.write!(temp_xml_path, xml)

        chain_path = Path.join(cert_dir, "chain.pem")

        openssl_args =
          if File.exists?(chain_path) do
            [
              "smime",
              "-sign",
              "-signer",
              cert_path,
              "-inkey",
              key_path,
              "-certfile",
              chain_path,
              "-nodetach",
              "-outform",
              "der",
              "-in",
              temp_xml_path
            ]
          else
            [
              "smime",
              "-sign",
              "-signer",
              cert_path,
              "-inkey",
              key_path,
              "-nodetach",
              "-outform",
              "der",
              "-in",
              temp_xml_path
            ]
          end

        case System.cmd("openssl", openssl_args) do
          {signed_der, 0} ->
            File.rm(temp_xml_path)
            signed_der

          {error_log, status} ->
            File.rm(temp_xml_path)

            Logger.warning(
              "OpenSSL configuration profile signing failed with status #{status}: #{error_log}. Serving unsigned xml instead."
            )

            xml
        end

      true ->
        xml
    end
  end

  defp generate_self_signed_cert(cert_dir, phx_host) do
    key_path = Path.join(cert_dir, "privkey.pem")
    cert_path = Path.join(cert_dir, "cert.pem")

    if not File.exists?(key_path) or not File.exists?(cert_path) do
      File.mkdir_p!(cert_dir)

      Logger.info(
        "Self-signed configuration profile signing certs not found. Creating dynamic certs in config/certs/..."
      )

      custom_cnf = """
      [req]
      distinguished_name = req_distinguished_name
      prompt = no

      [req_distinguished_name]
      CN = #{phx_host}
      O = Hermit DNS
      OU = Secure Provisioning
      C = US
      """

      cnf_path = Path.join(cert_dir, "openssl.cnf")
      File.write!(cnf_path, custom_cnf)

      case System.cmd("openssl", [
             "req",
             "-new",
             "-newkey",
             "rsa:2048",
             "-days",
             "3650",
             "-nodes",
             "-x509",
             "-config",
             cnf_path,
             "-keyout",
             key_path,
             "-out",
             cert_path
           ]) do
        {_output, 0} ->
          File.rm(cnf_path)
          Logger.info("Signing certificates generated successfully at config/certs/")

        {err, status} ->
          File.rm(cnf_path)
          Logger.error("Failed to generate profile signing certs (code #{status}): #{err}")
      end
    end
  end

  defp get_dns_packet(_conn, %{"dns" => dns_b64} = _params) do
    # GET method uses base64url query param
    case Base.url_decode64(dns_b64, padding: false) do
      {:ok, binary} -> {:ok, binary}
      _ -> {:error, :bad_base64}
    end
  end

  defp get_dns_packet(conn, _params) do
    # POST method body contains raw binary dns message
    content_type = get_header(conn, "content-type")

    if content_type == "application/dns-message" do
      case Plug.Conn.read_body(conn) do
        {:ok, body, _conn} -> {:ok, body}
        {:error, reason} -> {:error, reason}
      end
    else
      {:error, :missing_dns_parameter}
    end
  end

  defp render_mobile_config_page(conn, endpoint, server_url) do
    conn
    |> put_resp_content_type("text/html")
    |> send_resp(200, """
    <!DOCTYPE html>
    <html lang="en" data-theme="dark">
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title>Hermit DNS Endpoint: #{endpoint.name}</title>
      <script src="https://cdn.tailwindcss.com"></script>
    </head>
    <body class="bg-slate-950 text-slate-100 font-sans min-h-screen flex items-center justify-center p-4">
      <div class="max-w-md w-full bg-slate-900 border border-slate-800 rounded-2xl p-6 shadow-xl space-y-6">
        <div class="text-center space-y-2">
          <span class="text-4xl">🔒</span>
          <h2 class="text-xl font-bold tracking-tight text-emerald-400">Hermit DNS Endpoint</h2>
          <p class="text-xs text-slate-400 font-mono">#{endpoint.name}</p>
        </div>

        <div class="bg-slate-950/60 rounded-xl p-4 border border-slate-800/80 space-y-3">
          <h3 class="text-xs font-semibold uppercase tracking-wider text-slate-400">Secure DoH Address</h3>
          <code class="block bg-slate-950 px-3 py-2 rounded text-xs text-emerald-400 break-all font-mono select-all">
            #{server_url}
          </code>
        </div>

        <div class="space-y-3">
          <h3 class="text-xs font-semibold uppercase tracking-wider text-slate-400">iOS / macOS Auto Setup</h3>
          <p class="text-xs text-slate-400">
            Download the Apple Provisioning profile below. Once downloaded, open your Settings app and install the profile to apply system-wide secure DNS filtering.
          </p>
          <a href="#{server_url}/mobileconfig" class="block w-full text-center bg-emerald-600 hover:bg-emerald-500 active:bg-emerald-700 text-white py-2.5 rounded-lg text-sm font-semibold transition-colors cursor-pointer">
            ⬇️ Download Profile (.mobileconfig)
          </a>
        </div>

        <div class="border-t border-slate-800 pt-4 text-center">
          <p class="text-[10px] text-slate-500">Hermit Encrypted DNS System &bull; v0.1.0-alpha</p>
        </div>
      </div>
    </body>
    </html>
    """)
  end

  defp generate_uuid() do
    # Generates a standard UUID version 4
    <<a::32, b::16, c::16, d::16, e::48>> = :crypto.strong_rand_bytes(16)
    c = (c &&& 0x0FFF) ||| 0x4000
    d = (d &&& 0x3FFF) ||| 0x8000

    List.to_string(
      :io_lib.format("~8.16.0b-~4.16.0b-~4.16.0b-~4.16.0b-~12.16.0b", [a, b, c, d, e])
    )
  end

  defp get_client_ip(conn) do
    with nil <- get_header(conn, "cf-connecting-ip") |> parse_ip(),
         nil <- get_header(conn, "true-client-ip") |> parse_ip(),
         nil <- get_header(conn, "x-real-ip") |> parse_ip(),
         nil <- get_header(conn, "x-forwarded-for") |> parse_xff_header(),
         do: conn.remote_ip
  end

  defp get_header(conn, name) do
    case Plug.Conn.get_req_header(conn, name) do
      [value | _] -> value
      [] -> nil
    end
  end

  defp parse_xff_header(nil), do: nil

  defp parse_xff_header(val) do
    # Format: client, proxy1, proxy2
    val
    |> String.split(",")
    |> List.first()
    |> String.trim()
    |> parse_ip()
  end

  defp parse_ip(ip_str) when is_binary(ip_str) do
    case :inet.parse_address(String.to_charlist(ip_str)) do
      {:ok, ip} -> ip
      _ -> nil
    end
  end

  defp parse_ip(_), do: nil

  defp get_device_name(conn) do
    with nil <- get_header(conn, "x-device-name"),
         nil <- get_header(conn, "x-device-model") do
      ua = get_header(conn, "user-agent") || ""

      cond do
        String.contains?(ua, "iPhone") -> "iPhone"
        String.contains?(ua, "iPad") -> "iPad"
        String.contains?(ua, "Macintosh") -> "Mac"
        String.contains?(ua, "Windows") -> "Windows PC"
        String.contains?(ua, "Android") -> "Android"
        String.contains?(ua, "Linux") -> "Linux"
        true -> "Generic Device"
      end
    end
  end

  defp build_servfail_packet(query_packet) do
    case Hermit.Dns.Packet.parse(query_packet) do
      {:ok, query} ->
        servfail = Hermit.Dns.Packet.build_nxdomain(query.id, query.query_record)
        Hermit.Dns.Packet.patch_rcode(servfail, 2)

      _ ->
        if byte_size(query_packet) >= 12 do
          <<id::binary-size(2), _::binary>> = query_packet
          <<id::binary, 0x81, 0x82, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00>>
        else
          <<0x00, 0x00, 0x81, 0x82, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00>>
        end
    end
  end
end
